### ISSUE TITLE
dvrk_xr_ros_bridge.py 

### ISSUE THREAD

**Issue by fanke1213812138** [jhu-dvrk/dvrk-xr#2]
When I ran the dvrk_xr_ros_bridge.py, I got this error.
Thank you very much!
[ERROR] [1630682447.687229]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7fe0027ad990>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 302, in add
    self.signalMessage(*msgs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "./dvrk_xr_ros_bridge.py", line 126, in callback
    jaw_string_msg = extract_jaw_data(jaw_raw)
  File "./dvrk_xr_ros_bridge.py", line 92, in extract_jaw_data
    name_json = "\"" + name_data[0][1] + "\""
  File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 390, in __getitem__
    return self.__toklist[i]
IndexError: list index out of range

**Comment by adeguet1** [comment]
Please provide a bit more information.  Which version of the dVRK code are you using?  It seems dvrk_xr_ros_bridge.py is getting an ampty message for the jaw angle.  Maybe this code needs to be ported for dVRK 2.x and/or the dVRK ROS node is not running?


On Sep 3, 2021, at 11:24, fanke1213812138 ***@***.******@***.***>> wrote:



When I ran the dvrk_xr_ros_bridge.py, I got this error.
Thank you very much!
[ERROR] [1630682447.687229]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7fe0027ad990>>
Traceback (most recent call last):
File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
cb(msg)
File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/init.py", line 76, in callback
self.signalMessage(msg)
File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/init.py", line 58, in signalMessage
cb(*(msg + args))
File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/init.py", line 302, in add
self.signalMessage(msgs)
File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/init.py", line 58, in signalMessage
cb((msg + args))
File "./dvrk_xr_ros_bridge.py", line 126, in callback
jaw_string_msg = extract_jaw_data(jaw_raw)
File "./dvrk_xr_ros_bridge.py", line 92, in extract_jaw_data
name_json = """ + name_data[0][1] + """
File "/usr/lib/python2.7/dist-packages/pyparsing.py", line 390, in getitem
return self.__toklist[i]
IndexError: list index out of range

**Comment by fanke1213812138** [comment]
Thank you very much for your reply.

The version is 1.7. Maybe it's a problem. The ROS node is running. May I ask if the message of /dvrk/PSM1/state_joint_current topic can be directly used in simulations like Uniy 3D or Gazebo? Do I need any conversion?

**Comment by adeguet1** [comment]
I must admit I never really looked at the dvrk-xr code but I’ll do my best to help.

Can you run `rostopic echo /dvrk/PSM1/state_joint_current` to see it the dVRK console is publishing useful values?


On Sep 3, 2021, at 12:40, fanke1213812138 ***@***.******@***.***>> wrote:



Thank you very much for your reply.

The version is 1.7. Maybe it's a problem. The ROS node is running. May I ask if the message of /dvrk/PSM1/state_joint_current topic can be directly used in simulations like Uniy 3D or Gazebo? Do I need any conversion?

**Comment by fanke1213812138** [comment]
Yes, the topic is publishing useful Jointstate information with 6 values of position etc. So can I use that in other simulations directly? But all the joints move in a wrong way. I used ROS-SHARP by [siemens](https://github.com/siemens/ros-sharp), with a joint_state_subscriber and jont_state_writers. Or could you give me a hint to simulate dVRK in some platforms? Anything would be appreciated. Than you very much for your help! 
![Screenshot from 2021-09-03 17-30-06](https://user-images.githubusercontent.com/42082278/132088057-de663d8e-077a-472b-a22f-1b9922333860.png)
